language: objective-c

rvm:
    - 2.2.2

before_install:
    - rvm @global do gem uninstall bundler --all --executables
    - gem uninstall bundler --all --executables
    - gem install bundler --version '1.11.2'
    - gem install cocoapods -v '1.3.1'
    - gem install slather
    - brew update
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
    - pod install

xcode_workspace: Snowplow.xcworkspace
xcode_scheme: Snowplow
xcode_sdk:
    - iphonesimulator

after_success: slather
